#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Microservice for Control Sala
  description: Golang + MySQL
  license:
    name: HangedDraw, 2020-I

paths:
  /palabra:
    get:
      summary: Mostrar la palabra a dibujar
      operationId: MostrarPalabra
      responses:
        '200':
          description: Palabra
        '400':
          description Bad Request
    post:
      summary: Dar los puntos por acertar la palabra
      operationId: palabraAcertada
      parameters:
        - name: IdJugador
          in: path
          required: true
          description: el id del jugador que acerto la palabra
          type: string
          schema:
            $ref: './ControlSala/main'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request

  /Puntaje:
    get:
      summary: Muestra el puntaje de todos los jugadores de la sala
      operationId: Puntajes
      responses:
        '200':
          description: array Puntajes
        '400':
          description Bad Request


  /jugador/{id}:
    post:
      summary: agrega un jugador a la sala
      operationId: AgregarJugador
      parameters:
        - name: IdJugador
          in: path
          required: true
          description: idJugador que entro a la sala
          schema:
            $red: './ControlSala/main'
    delete:
      summary: Borra a un jugadar de la sala
      operationId: BorrarJugador
      parameters:
        - name: IdJugador
          in: path
          description: idJugador que salio de la sala
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          '404':
            description: Not Found



  #definitions
  definitions:
    Jugador:
      type: Object
      properties:
        idJugador:
          type: integer
        puntaje:
          type: integer
        Dibujado:
          type: integer

    Sala:
      type: Object
      properties:
        IdSala:
          type: integer
        Jugador1:
          type: integer
        Jugador2:
          type: integer
        Jugador3:
          type: integer

# Errors
  ErrorModel:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: number
      description:
        type: object
